
use gene::config;

#
# Add a comment header to the $code string to say how it was generated.
#
# $commentChar is the string beginning each line of comment.
# Returns the concatenation of the header and $code.
#
sub addHeaderText(Str :$code, Str :$commentChar = '#') is export
{

    # text of the header
    my $text = q:to/END/;

        This code has been automatically generated by RaQt_maker V_VERSION_.

        Rather than manually modify this file, it should be preferable to

            - 1) Modify the source files available here:
                _REPOSITORY_

            - 2) Regenerate the whole code.

        END

    # Replace the keywords
    $text ~~ s/_VERSION_/$geneVersion/;
    $text ~~ s/_REPOSITORY_/$repository/;

    # Set text as a comment
    my $comment = [~] ($commentChar ~ " ") <<~>> $text.lines <<~>> "\n";

    # Output code with header
    return $comment ~ $code;
}


